### ISSUE TITLE
about running time

### ISSUE THREAD

**Issue by weiyangdaren** [chenyilun95/DSGN2#19]
Thank you for your amazing work! I conducted an evaluation on the running time of DSGN_backbone on TITAN RTX, but I got different results from the paper. I found two differences. One is that the feature extraction took about 145ms by using ResNet34, and the result of 116ms was obtained by using ResNet18; the other is that the function named "forward_front_surface_depth_head" took an additional 100ms, but its result seems to be only used to calculate the depth loss during training, should I remove it when inference?

**Comment by chenyilun95** [comment]
1. The speed difference might be due to different hardware setups. The speed of R34-DSGN++ and R18-DSGN++ are shown in Sec 4.5. Maybe you can compare the overall speed first and analyze the detailed speed of each component in the section. You could also try isolating the effects of data loader (setting num of data workers=0).
2. Yes, the depth head is removed during inference.
